// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	DeleteTodo(ctx context.Context, id int64) error
	GetAllTodos(ctx context.Context) ([]Todo, error)
	GetTodoByID(ctx context.Context, id int64) (Todo, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) error
}

var _ Querier = (*Queries)(nil)
